import os
import json

json_path = './train.json'

with open(json_path, 'r') as f:
    train_datalist = json.load(f)
    
data_dict = {}
for item in train_datalist:
    image_files = item['image_files']
    num_images = len(image_files)
    for i in range(num_images):
        object_class = item['object_class'][i]; action_class = item['action_class'][i]
        if (object_class, action_class) not in data_dict.keys():
            data_dict[(object_class, action_class)] = []
        result_path = os.path.join('/home/user/smh/New_Nameonly_CL/dataset/Bongard-HOI', image_files[i])
        data_dict[(object_class, action_class)].append(result_path)

for key, v in data_dict.items():
    data_dict[key] = list(set(v))
    print(f"{key}: {len(data_dict[key])}")


tuples_to_prompts = {
    ('orange', 'eat'): "A person eating an orange",
    ('orange', 'peel'): "Peeling an orange",
    ('orange', 'wash'): "Washing an orange",
    ('orange', 'hold'): "Holding an orange",
    ('orange', 'no_interaction'): "An orange",
    ('orange', 'squeeze'): "Squeezing an orange",
    ('orange', 'cut'): "Cutting an orange",
    ('toilet', 'clean'): "Cleaning a toilet",
    ('toilet', 'sit_on'): "Sitting on a toilet",
    ('toilet', 'wash'): "Washing a toilet",
    ('toilet', 'flush'): "Flushing a toilet",
    ('toilet', 'stand_on'): "Standing on a toilet",
    ('toilet', 'open'): "Opening a toilet",
    ('teddy_bear', 'hold'): "Holding a teddy bear",
    ('teddy_bear', 'no_interaction'): "A teddy bear",
    ('teddy_bear', 'kiss'): "Kissing a teddy bear",
    ('teddy_bear', 'hug'): "Hugging a teddy bear",
    ('broccoli', 'hold'): "Holding broccoli",
    ('broccoli', 'eat'): "Eating broccoli",
    ('broccoli', 'no_interaction'): "Broccoli",
    ('broccoli', 'wash'): "Washing broccoli",
    ('broccoli', 'stir'): "Stirring broccoli",
    ('broccoli', 'cut'): "Cutting broccoli",
    ('carrot', 'hold'): "Holding a carrot",
    ('carrot', 'peel_or_cut'): "Peeling or cutting a carrot",
    ('carrot', 'wash'): "Washing a carrot",
    ('carrot', 'cook'): "Cooking a carrot",
    ('carrot', 'no_interaction'): "A carrot",
    ('carrot', 'eat'): "Eating a carrot",
    ('wine_glass', 'sip'): "Sipping from a wine glass",
    ('wine_glass', 'wash'): "Washing a wine glass",
    ('wine_glass', 'fill'): "Filling a wine glass",
    ('car', 'drive'): "Driving a car",
    ('car', 'wash'): "Washing a car",
    ('car', 'no_interaction'): "A car",
    ('car', 'inspect'): "Inspecting a car",
    ('cat', 'pet'): "Petting a cat",
    ('cat', 'kiss'): "Kissing a cat",
    ('cat', 'chase'): "Chasing a cat",
    ('cat', 'hold'): "Holding a cat",
    ('cat', 'feed'): "Feeding a cat",
    ('cat', 'wash'): "Washing a cat",
    ('train', 'exit'): "Exiting a train",
    ('train', 'ride'): "Riding a train",
    ('train', 'sit_on'): "Sitting on a train",
    ('boat', 'sit_on'): "Sitting on a boat",
    ('boat', 'drive'): "Driving a boat",
    ('boat', 'sail'): "Sailing a boat",
    ('boat', 'repair'): "Repairing a boat",
    ('boat', 'tie'): "Tying a boat",
    ('boat', 'board'): "Boarding a boat",
    ('airplane', 'exit'): "Exiting an airplane",
    ('airplane', 'no_interaction'): "An airplane",
    ('airplane', 'inspect'): "Inspecting an airplane",
    ('airplane', 'wash'): "Washing an airplane",
    ('airplane', 'ride'): "Riding an airplane",
    ('airplane', 'load'): "Loading an airplane",
    ('tv', 'control'): "Controlling a TV",
    ('tv', 'watch'): "Watching TV",
    ('tv', 'repair'): "Repairing a TV",
    ('tv', 'no_interaction'): "A TV",
    ('person', 'teach'): "A person teaching",
    ('person', 'hug'): "A person hugging",
    ('person', 'hold'): "A person holding",
    ('person', 'stab'): "A person stabbing",
    ('person', 'carry'): "A person carrying",
    ('person', 'lick'): "A person licking",
    ('umbrella', 'stand_under'): "Standing under an umbrella",
    ('umbrella', 'sit_under'): "Sitting under an umbrella",
    ('umbrella', 'no_interaction'): "An umbrella",
    ('umbrella', 'hold'): "Holding an umbrella",
    ('knife', 'cut_with'): "Cutting with a knife",
    ('knife', 'no_interaction'): "A knife",
    ('refrigerator', 'clean'): "Cleaning a refrigerator",
    ('refrigerator', 'move'): "Moving a refrigerator",
    ('refrigerator', 'no_interaction'): "A refrigerator",
    ('refrigerator', 'open'): "Opening a refrigerator",
    ('refrigerator', 'hold'): "Holding a refrigerator",
    ('kite', 'fly'): "Flying a kite",
    ('kite', 'hold'): "Holding a kite",
    ('laptop', 'type_on'): "Typing on a laptop",
    ('laptop', 'repair'): "Repairing a laptop",
    ('laptop', 'no_interaction'): "A laptop",
    ('laptop', 'open'): "Opening a laptop",
    ('cow', 'pet'): "Petting a cow",
    ('cow', 'lasso'): "Lassoing a cow",
    ('cow', 'ride'): "Riding a cow",
    ('cow', 'hug'): "Hugging a cow",
    ('cake', 'make'): "Making a cake",
    ('cake', 'no_interaction'): "A cake",
    ('cake', 'eat'): "Eating a cake",
    ('cake', 'cut'): "Cutting a cake",
    ('cake', 'blow'): "Blowing on a cake",
    ('cake', 'hold'): "Holding a cake",
    ('donut', 'eat'): "Eating a donut",
    ('donut', 'hold'): "Holding a donut",
    ('donut', 'no_interaction'): "A donut",
    ('donut', 'make'): "Making a donut",
    ('donut', 'cut'): "Cutting a donut",
    ('sandwich', 'eat'): "Eating a sandwich",
    ('sandwich', 'make'): "Making a sandwich",
    ('sandwich', 'cut'): "Cutting a sandwich",
    ('sandwich', 'no_interaction'): "A sandwich",
    ('snowboard', 'adjust'): "Adjusting a snowboard",
    ('snowboard', 'wear'): "Wearing a snowboard",
    ('snowboard', 'ride'): "Riding a snowboard",
    ('snowboard', 'no_interaction'): "A snowboard",
    ('snowboard', 'hold'): "Holding a snowboard",
    ('bird', 'hold'): "Holding a bird",
    ('bird', 'watch'): "Watching a bird",
    ('bird', 'feed'): "Feeding a bird",
    ('bird', 'no_interaction'): "A bird",
    ('bird', 'chase'): "Chasing a bird",
    ('bear', 'feed'): "Feeding a bear",
    ('bear', 'no_interaction'): "A bear",
    ('bear', 'hunt'): "Hunting a bear",
    ('bear', 'watch'): "Watching a bear",
    ('hot_dog', 'make'): "Making a hot dog",
    ('hot_dog', 'eat'): "Eating a hot dog",
    ('hot_dog', 'no_interaction'): "A hot dog",
    ('clock', 'hold'): "Holding a clock",
    ('clock', 'no_interaction'): "A clock",
    ('clock', 'set'): "Setting a clock",
    ('clock', 'check'): "Checking a clock",
    ('bicycle', 'ride'): "Riding a bicycle",
    ('bicycle', 'hold'): "Holding a bicycle",
    ('bicycle', 'straddle'): "Straddling a bicycle",
    ('bicycle', 'wash'): "Washing a bicycle",
    ('bicycle', 'walk'): "Walking a bicycle",
    ('bicycle', 'hop_on'): "Hopping on a bicycle",
    ('bicycle', 'no_interaction'): "A bicycle",
    ('bicycle', 'carry'): "Carrying a bicycle",
    ('skateboard', 'carry'): "Carrying a skateboard",
    ('skateboard', 'ride'): "Riding a skateboard",
    ('skateboard', 'no_interaction'): "A skateboard",
    ('banana', 'eat'): "Eating a banana",
    ('banana', 'peel'): "Peeling a banana",
    ('banana', 'inspect'): "Inspecting a banana",
    ('banana', 'no_interaction'): "A banana",
    ('banana', 'buy'): "Buying a banana",
    ('banana', 'cut'): "Cutting a banana",
    ('elephant', 'ride'): "Riding an elephant",
    ('elephant', 'no_interaction'): "An elephant",
    ('elephant', 'pet'): "Petting an elephant",
    ('elephant', 'hop_on'): "Hopping on an elephant",
    ('elephant', 'wash'): "Washing an elephant",
    ('elephant', 'hold'): "Holding an elephant",
    ('elephant', 'watch'): "Watching an elephant",
    ('elephant', 'hug'): "Hugging an elephant",
    ('elephant', 'walk'): "Walking an elephant",
    ('elephant', 'kiss'): "Kissing an elephant",
    ('cup', 'hold'): "Holding a cup",
    ('cup', 'drink_with'): "Drinking with a cup",
    ('cup', 'fill'): "Filling a cup",
    ('dog', 'hold'): "Holding a dog",
    ('dog', 'walk'): "Walking a dog",
    ('dog', 'hug'): "Hugging a dog",
    ('dog', 'wash'): "Washing a dog",
    ('dog', 'feed'): "Feeding a dog",
    ('dog', 'dry'): "Drying a dog",
    ('dog', 'straddle'): "Straddling a dog",
    ('dog', 'run'): "Running with a dog",
    ('dog', 'no_interaction'): "A dog",
    ('dog', 'chase'): "Chasing a dog",
    ('dog', 'straddle,pet'): "Straddling and petting a dog",
    ('dining_table', 'sit_at'): "Sitting at a dining table",
    ('dining_table', 'eat_at'): "Eating at a dining table",
    ('dining_table', 'clean'): "Cleaning a dining table",
    ('keyboard', 'type_on'): "Typing on a keyboard",
    ('keyboard', 'clean'): "Cleaning a keyboard",
    ('bus', 'exit'): "Exiting a bus",
    ('bus', 'no_interaction'): "A bus",
    ('bus', 'wave'): "Waving at a bus",
    ('bus', 'inspect'): "Inspecting a bus",
    ('bus', 'board'): "Boarding a bus",
    ('bus', 'wash'): "Washing a bus",
    ('skis', 'ride'): "Riding skis",
    ('skis', 'carry'): "Carrying skis",
    ('skis', 'no_interaction'): "Skis",
    ('skis', 'jump'): "Jumping with skis",
    ('skis', 'inspect'): "Inspecting skis",
    ('stop_sign', 'hold'): "Holding a stop sign",
    ('stop_sign', 'no_interaction'): "A stop sign",
    ('giraffe', 'feed'): "Feeding a giraffe",
    ('giraffe', 'ride'): "Riding a giraffe",
    ('giraffe', 'watch'): "Watching a giraffe",
    ('giraffe', 'no_interaction'): "A giraffe",
    ('giraffe', 'pet'): "Petting a giraffe",
    ('vase', 'make'): "Making a vase",
    ('vase', 'hold'): "Holding a vase",
    ('sports_ball', 'spin'): "Spinning a sports ball",
    ('sports_ball', 'dribble'): "Dribbling a sports ball",
    ('sports_ball', 'hit'): "Hitting a sports ball",
    ('sports_ball', 'catch'): "Catching a sports ball",
    ('sports_ball', 'kick'): "Kicking a sports ball",
    ('sports_ball', 'sign'): "Signing a sports ball",
    ('sports_ball', 'no_interaction'): "A sports ball",
    ('bowl', 'stir'): "Stirring a bowl",
    ('bowl', 'hold'): "Holding a bowl",
    ('bowl', 'no_interaction'): "A bowl",
    ('bowl', 'wash'): "Washing a bowl",
    ('bowl', 'eat_with'): "Eating with a bowl",
    ('bottle', 'drink_with'): "Drinking with a bottle",
    ('bottle', 'hold'): "Holding a bottle",
    ('bottle', 'inspect'): "Inspecting a bottle",
    ('bottle', 'no_interaction'): "A bottle",
    ('bottle', 'open'): "Opening a bottle",
    ('motorcycle', 'ride'): "Riding a motorcycle",
    ('motorcycle', 'wash'): "Washing a motorcycle",
    ('motorcycle', 'inspect'): "Inspecting a motorcycle",
    ('motorcycle', 'sit_on'): "Sitting on a motorcycle",
    ('motorcycle', 'jump'): "Jumping on a motorcycle",
    ('motorcycle', 'no_interaction'): "A motorcycle",
    ('motorcycle', 'park'): "Parking a motorcycle",
    ('motorcycle', 'walk'): "Walking with a motorcycle",
    ('motorcycle', 'hold'): "Holding a motorcycle",
    ('spoon', 'lick_or_sip'): "Licking or sipping with a spoon",
    ('spoon', 'hold'): "Holding a spoon",
    ('spoon', 'wash'): "Washing a spoon",
    ('suitcase', 'drag'): "Dragging a suitcase",
    ('suitcase', 'pack'): "Packing a suitcase",
    ('suitcase', 'no_interaction'): "A suitcase",
    ('suitcase', 'hold'): "Holding a suitcase",
    ('suitcase', 'hug'): "Hugging a suitcase",
    ('bed', 'sit_on'): "Sitting on a bed",
    ('bed', 'lie_on'): "Lying on a bed",
    ('bed', 'clean'): "Cleaning a bed",
    ('bed', 'no_interaction'): "A bed"
}

result_dict = {}
sum = 0
for k, v in tuples_to_prompts.items():
    result_dict[k] = (v, len(data_dict[k]))
    sum += len(data_dict[k])
breakpoint()